# Generated by Django 3.2.6 on 2021-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('flight_date', models.DateField(max_length=10)),
                ('flight_time', models.TimeField(max_length=8)),
                ('flight_direction', models.CharField(max_length=100)),
                ('aircraft_type', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='DepartureFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('flight_date', models.DateField(max_length=10)),
                ('flight_time', models.TimeField(max_length=8)),
                ('flight_direction', models.CharField(max_length=100)),
                ('aircraft_type', models.CharField(max_length=4)),
            ],
        ),
    ]
