# Generated by Django 3.2.6 on 2021-11-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('iata', models.CharField(max_length=4)),
            ],
        ),
    ]
