# Generated by Django 3.2.6 on 2021-12-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_project', '0002_destinationcityname'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcityname',
            name='country',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='arrivalflight',
            name='aircraft_type',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='arrivalflight',
            name='flight_date',
            field=models.DateField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrivalflight',
            name='flight_direction',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='arrivalflight',
            name='flight_number',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrivalflight',
            name='flight_time',
            field=models.TimeField(default='N/A', max_length=8),
        ),
        migrations.AlterField(
            model_name='departureflight',
            name='aircraft_type',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='departureflight',
            name='flight_date',
            field=models.DateField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='departureflight',
            name='flight_direction',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='departureflight',
            name='flight_number',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='departureflight',
            name='flight_time',
            field=models.TimeField(default='N/A', max_length=8),
        ),
        migrations.AlterField(
            model_name='destinationcityname',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationcityname',
            name='iata',
            field=models.CharField(default='N/A', max_length=4),
        ),
    ]
