# Generated by Django 3.2.6 on 2021-12-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_project', '0003_auto_20211201_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DestinationCityName',
            new_name='Destination',
        ),
    ]
